[package]
name = "assets"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "assets"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
csv.workspace = true
chrono.workspace = true
clap.workspace = true
dot_vox.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
tokio.workspace = true
base64.workspace = true
dotenv.workspace = true
