[package]
name = "game"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "game"
path = "src/main.rs"

[lib]
name = "game"
crate-type = ["cdylib", "rlib"]

[dependencies]
app = { path = "../app" }
renderer = { path = "../renderer" }
cube = { path = "../cube" }
glow = "0.14"
glam = "0.29"
winit = "0.30"
egui = "0.29"
egui-winit = "0.29"
egui_glow = "0.29"
gilrs = "0.11"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
libloading = "0.8"
notify = "6.1"
notify-debouncer-mini = "0.4"

[target.'cfg(target_os = "linux")'.dependencies]
winit = { version = "0.30", features = ["x11"] }
